apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: migrate
          image: sellinios/backend:20240715082915
          command: ["python"]
          args: ["manage.py", "migrate"]
          env:
            - name: POSTGRES_DB
              value: aethradb
            - name: POSTGRES_USER
              value: sellinios
            - name: POSTGRES_PASSWORD
              value: faidra123!@#
            - name: POSTGRES_HOST
              value: postgres
      containers:
        - name: backend
          image: sellinios/backend:20240715082915
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB
              value: aethradb
            - name: POSTGRES_USER
              value: sellinios
            - name: POSTGRES_PASSWORD
              value: faidra123!@#
            - name: POSTGRES_HOST
              value: postgres
