apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: backend
type: Opaque
data:
  SECRET_KEY: eW91ci1hY3R1YWwtc2VjcmV0LWtleQ==
  POSTGRES_DB: YWV0aHJhZGI=
  POSTGRES_USER: c2VsbGluaW9z
  POSTGRES_PASSWORD: ZmFpZHJhMTIzIUAj
