apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sellinios/frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          value: "https://backend-service.backend.svc.cluster.local:8000"
        volumeMounts:
        - mountPath: /etc/nginx/certs
          name: tls-certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: kairos-tls
      imagePullSecrets:
        - name: dockerhub-secret