apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: backend
type: Opaque
data:
  POSTGRES_DB: YWV0aHJhZGI=
  POSTGRES_USER: c2VsbGluaW9z
  POSTGRES_PASSWORD: ZmFpZHJhMTIzIUAj
  SECRET_KEY: ZkIyIW5xJiF2IzNqIWpSQkB2KjhkIXNLIWpAbEEqOWdF
