apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kairos-tls
  namespace: kairos
spec:
  secretName: kairos-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kairos.gr
  dnsNames:
  - kairos.gr
