# Generated by Django 5.0.7 on 2024-07-20 05:12

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Geographic Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeographicDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('level_name', models.CharField(max_length=255)),
                ('name_variations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('confirmed', models.BooleanField(default=False)),
                ('geographic_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='geography.geographicdata')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='geography.geographicdivision')),
            ],
            options={
                'verbose_name_plural': 'Geographic Divisions',
                'unique_together': {('name', 'parent', 'level_name')},
            },
        ),
        migrations.CreateModel(
            name='GeographicPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('admin_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='geography.geographicdivision')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='geography.geographiccategory')),
            ],
            options={
                'verbose_name': 'Geographic Place',
                'verbose_name_plural': 'Geographic Places',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeocodeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geocode_result', models.JSONField(blank=True, null=True)),
                ('geocode_last_updated', models.DateTimeField(blank=True, null=True)),
                ('geographic_place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geocode', to='geography.geographicplace')),
            ],
            options={
                'verbose_name': 'Geocode Result',
                'verbose_name_plural': 'Geocode Results',
            },
        ),
        migrations.CreateModel(
            name='GeographicPlaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='geography.geographicplace')),
            ],
            options={
                'verbose_name': 'Geographic Place Translation',
                'db_table': 'geography_geographicplace_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GeographicCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='geography.geographiccategory')),
            ],
            options={
                'verbose_name': 'geographic category Translation',
                'db_table': 'geography_geographiccategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='geographicplace',
            index=models.Index(fields=['longitude', 'latitude'], name='geography_g_longitu_45f7ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='geographicplacetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
