# Generated by Django 5.0.7 on 2024-07-20 05:12

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GFSForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.CharField(max_length=10)),
                ('hour', models.CharField(max_length=2)),
                ('utc_cycle_time', models.CharField(choices=[('00', '00'), ('06', '06'), ('12', '12'), ('18', '18')], max_length=2)),
                ('forecast_data', models.JSONField()),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GFSParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('level_layer', models.CharField(max_length=255)),
                ('parameter', models.CharField(max_length=255)),
                ('forecast_valid', models.CharField(default='N/A', max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'unique_together': {('number', 'level_layer', 'parameter')},
            },
        ),
    ]
